name := "netbird-coredns"
image := "nb-dns:dev"
k3d-config := "k3d.yaml"
kubeconfig := "~/.kube/config"

# List all commands
list:
    just --list --unsorted

########################################################
# K3d

# Create k3d cluster
create-cluster:
    k3d cluster create {{ name }} --config {{ k3d-config }}

# Delete k3d cluster
delete-cluster:
    k3d cluster delete {{ name }}

# Import image into k3d cluster
import-image:
    k3d image import {{ image }} --cluster {{ name }}

########################################################
# Helm

_helm *args:
    helm {{ args }} \
        --namespace {{ name }} \
        --kubeconfig {{ kubeconfig }} \
        --kube-context k3d-{{ name }}

# Install chart
install:
    just _helm upgrade \
        --install {{ name }} . \
        --create-namespace \
        --values values.yaml \
        --values values-dev.yaml

# Uninstall chart
uninstall:
    just _helm uninstall {{ name }}
